<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aqila Gema Nuswantoro">
<meta name="dcterms.date" content="2024-01-25">

<title>Hubungan antara Pendapatan Masyarakat dengan Kesejahteraan Masyarakat di Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hubungan antara Pendapatan Masyarakat dengan Kesejahteraan Masyarakat di Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aqila Gema Nuswantoro </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 25, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Dalam era globalisasi saat ini, pertumbuhan ekonomi dan pendapatan masyarakat dianggap sebagai ukuran kemajuan suatu negara. Namun, pertanyaan mendasar yang muncul adalah sejauh mana pendapatan tersebut berdampak pada kesejahteraan masyarakat? Seiring dengan peningkatan pendapatan, masih banyak orang yang merasa kesejahteraannya tidak meningkat dengan sebanding. Oleh karena itu, penelitian ini dilakukan untuk menyelidiki hubungan antara pendapatan dan kesejahteraan dengan lebih mendalam, agar kebijakan pembangunan dapat lebih sesuai dengan kebutuhan nyata masyarakat.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini akan berfokus kepada analisis statistik dari data pendapatan bersih pekerja bebas dan indikator kesejahteraan masyarakat. Dari penelitian ini dapat dilihat bagaimana uang yang didapatkan dari pekerjaan dapat mempengaruhi kehidupan sehari-hari.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Sejauh mana pendapatan dapat berkontribusi terhadap peningkatan kesejahteraan masyarakat?</li>
<li>Apakah pendapatan dapat berpengaruh secara signifikan terhadap kesejahteraan?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini adalah untuk menyelidiki hubungan antara pendapatan dengan kesejahteraan masyarakat secara mendalam. Melalui analisis data, penelitian ini bertujuan untuk mengidentifikasi sejauh mana jumlah pendapatan yang diperoleh dapat berkontribusi terhadap peningkatan kesejahteraan masyarakat secara keseluruhan.</p>
<p>Manfaat penelitian ini sangat signifikan dalam merancang kebijakan pembangunan yang lebih efektif dan inklusif. Dengan memahami secara jelas bagaimana pendapatan dapat mempengaruhi kesejahteraan, kebijakan dapat lebih terarah untuk meningkatkan kondisi hidup masyarakat sehingga dapat tercipta lingkungan sosial yang lebih adil dan berkelanjutan.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Dalam penelitian ini terdapat beberapa package yang akan digunakan, di antaranya sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Para ahli ekonomi pembangunan klasik (awal pasca perang dunia kedua) sepakat bahwa kesejahteraan dapat direpresentasikan melalui tingkat pendapatan. Pendapat ini berpijak pada teori ekonomi konvensional (neoklasik) bahwa kesejahteraan (utility) merupakan fungsi dari kombinasi konsumsi barang dan jasa dimana kombinasi konsumsi akan meningkat seiring dengan tambahan pendapatan (Case &amp; Fair, 2003).</p>
<p>Selain itu, tambahan pendapatan memungkinkan perekonomian negara untuk terus berkembang, baik dari segi tambahan jumlah barang dan jasa maupun ketersediaan lapangan pekerjaan (Rostow 1966).</p>
<p>Sederhananya, pendapatan merupakan salah satu faktor yang menggambarkan kesejahteraan masyarakat pada suatu negara. Semakin tinggi tingkat pendapatan negara, maka semakin tinggi pula kelas ekonomi masyarakat negara pada tersebut.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Data yang digunakan dalam penelitian ini adalah “Pendapatan Bersih Pekerja Bebas Menurut Provinsi dan Lapangan Pekerjaan Utama” dan “Indikator Kesejahteraan” dari sumber resmi Badan Pusat Statistik Indonesia.</p>
<p><img src="bps.jpg" class="img-fluid"></p>
<table class="table">
<thead>
<tr class="header">
<th>Provinsi</th>
<th>Pendapatan</th>
<th>Kesejahteraan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aceh</td>
<td>1843.24</td>
<td>100.87</td>
</tr>
<tr class="even">
<td>Sumatera Utara</td>
<td>1847.12</td>
<td>100.73</td>
</tr>
<tr class="odd">
<td>Sumatera Barat</td>
<td>1790.14</td>
<td>101.52</td>
</tr>
<tr class="even">
<td>Riau</td>
<td>2271.12</td>
<td>104.62</td>
</tr>
<tr class="odd">
<td>Jambi</td>
<td>2249.41</td>
<td>103.61</td>
</tr>
<tr class="even">
<td>Sumatera Selatan</td>
<td>1943.18</td>
<td>103.83</td>
</tr>
<tr class="odd">
<td>Bengkulu</td>
<td>1789.17</td>
<td>104.51</td>
</tr>
<tr class="even">
<td>Lampung</td>
<td>1636.66</td>
<td>104.54</td>
</tr>
<tr class="odd">
<td>Kep. Bangka Belitung</td>
<td>2441.48</td>
<td>105.62</td>
</tr>
<tr class="even">
<td>Kep. Riau</td>
<td>2925.36</td>
<td>103.55</td>
</tr>
<tr class="odd">
<td>DKI Jakarta</td>
<td>3713.24</td>
<td>101.34</td>
</tr>
<tr class="even">
<td>Jawa Barat</td>
<td>2236.12</td>
<td>102.72</td>
</tr>
<tr class="odd">
<td>Jawa Tengah</td>
<td>1565.86</td>
<td>101.03</td>
</tr>
<tr class="even">
<td>DI Yogyakarta</td>
<td>1420.39</td>
<td>98.02</td>
</tr>
<tr class="odd">
<td>Jawa Timur</td>
<td>1749.36</td>
<td>99.5</td>
</tr>
<tr class="even">
<td>Banten</td>
<td>2780.11</td>
<td>103.6</td>
</tr>
<tr class="odd">
<td>Bali</td>
<td>2248.56</td>
<td>100.69</td>
</tr>
<tr class="even">
<td>NTB</td>
<td>1732.87</td>
<td>100.45</td>
</tr>
<tr class="odd">
<td>NTT</td>
<td>1144.98</td>
<td>100.03</td>
</tr>
<tr class="even">
<td>Kalimantan Barat</td>
<td>1921.29</td>
<td>105.52</td>
</tr>
<tr class="odd">
<td>Kalimantan Tengah</td>
<td>2549.7</td>
<td>107.05</td>
</tr>
<tr class="even">
<td>Kalimantan Selatan</td>
<td>1844.36</td>
<td>102.35</td>
</tr>
<tr class="odd">
<td>Kalimantan Timur</td>
<td>2928.46</td>
<td>107.67</td>
</tr>
<tr class="even">
<td>Kalimantan Utara</td>
<td>2368.69</td>
<td>110.99</td>
</tr>
<tr class="odd">
<td>Sulawesi Utara</td>
<td>2102.77</td>
<td>104.43</td>
</tr>
<tr class="even">
<td>Sulawesi Tengah</td>
<td>1743.44</td>
<td>105.36</td>
</tr>
<tr class="odd">
<td>Sulawesi Selatan</td>
<td>2089.47</td>
<td>98.73</td>
</tr>
<tr class="even">
<td>Sulawesi Tenggara</td>
<td>1767.94</td>
<td>102.66</td>
</tr>
<tr class="odd">
<td>Gorontalo</td>
<td>1573.36</td>
<td>101.73</td>
</tr>
<tr class="even">
<td>Sulawesi Barat</td>
<td>1563.46</td>
<td>102.8</td>
</tr>
<tr class="odd">
<td>Maluku</td>
<td>1632.52</td>
<td>102.39</td>
</tr>
<tr class="even">
<td>Maluku Utara</td>
<td>1887.98</td>
<td>105.08</td>
</tr>
<tr class="odd">
<td>Papua Barat</td>
<td>2510.29</td>
<td>110.12</td>
</tr>
<tr class="even">
<td>Papua</td>
<td>2344.97</td>
<td>112.86</td>
</tr>
</tbody>
</table>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Dalam penelitian ini, metode yang digunakan adalah dengan melakukan analisis regresi untuk mengevaluasi hubungan antara pendapatan dan kesejahteraan masyarakat. Analisis ini dapat membantu untuk mengukur sejauh mana perubahan dalam pendapatan masyarakat dapat memprediksi perubahan dalam tingkat kesejahteraan. Spesifikasi yang dilakukan adalah :</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah Pendapatan dan <span class="math inline">\(x_t\)</span> adalah Kesejahteraan.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Untuk melakukan regresi, dilakukan pembacaan data terlebih dahulu sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"uas.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  Pendapatan Kesejahteraan
       &lt;dbl&gt;         &lt;dbl&gt;
1      1843.          101.
2      1847.          101.
3      1790.          102.
4      2271.          105.
5      2249.          104.
6      1943.          104.</code></pre>
</div>
</div>
<p>Berikut merupakan hubungan antara pendapatan dengan kesejahteraan masyarakat apabila divisualisasikan.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>Pendapatan,<span class="at">y=</span>Kesejahteraan)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"white"</span>,<span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Hubungan antara Pendapatan dengan Kesejahteraan Masyarakat"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Pendapatan Per Kapita"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Kesejahteraan Masyarakat"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber: Badan Pusat Statistik"</span>) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_dark</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Berikut ini adalah hasil regresi dari data yang telah dikumpulkan.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(Kesejahteraan<span class="sc">~</span>Pendapatan,<span class="at">data=</span>dat)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Kesejahteraan ~ Pendapatan, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4091 -2.0279 -0.2701  1.8567  8.5978 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 98.286198   2.252613  43.632   &lt;2e-16 ***
Pendapatan   0.002548   0.001060   2.404   0.0222 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.134 on 32 degrees of freedom
Multiple R-squared:  0.153, Adjusted R-squared:  0.1265 
F-statistic: 5.778 on 1 and 32 DF,  p-value: 0.02219</code></pre>
</div>
</div>
<p>Hasil regresi menunjukkan bahwa terdapat hubungan yang siginifikan antara pendapatan dengan kesejahteraan masyarakat. Koefisien regresi untuk pendapatan adalah 0.002548 dengan p-value 0.0222. Setiap kenaikan unit dalam pendapatan, berkontribusi sekitar 0.002548 unit dalam tingkat kesejahteraan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan hasil regresi yang menunjukkan bahwa pendapatan dan kesejahteraan saling mempengaruhi, maka dapat dilakukan upaya untuk meningkatkan ksejahteraan masyarakat melalui meningkatkan pendapatan melalui kebijakan pembangunan ekonomi, pelatihan keterampilan, dan penciptaan lapangan kerja. Selain itu, investasi dalam pendidikan juga dapat dikembangkan sehingga lebih efisien dan berkelanjutan.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Cahyadi, D. (t.t.). ANALISIS PENGUKURAN KESEJAHTERAAN DI INDONESIA. Jurnal Ilmiah Mahasiswa FEB Universitas Brawijaya. https://jimfeb.ub.ac.id/index.php/jimfeb/article/download/4083/3603</p>
<p>Indonesia, B. P. S. (t.t.-a). Indikator Kesejahteraan Rakyat 2023. Diambil 25 Januari 2024, dari https://www.bps.go.id/id/publication/2023/11/06/7807339c2dfaed0ca8e0beaa/indikator-kesejahteraan-rakyat-2023.html</p>
<p>Indonesia, B. P. S. (t.t.-b). Rata-rata Pendapatan Bersih Pekerja Bebas Menurut Provinsi dan Lapangan Pekerjaan Utama, 2023—Tabel Statistik. Diambil 25 Januari 2024, dari https://www.bps.go.id/id/statistics-table/1/MjE5NyMx/rata-rata-pendapatan-bersih-pekerja-bebas-menurut-provinsi-dan-lapangan-pekerjaan-utama-2023.html</p>
<p>Kenali Pengettian Pendapatan Nasional, Manfaat, &amp; Komponen. (t.t.). Diambil 25 Januari 2024, dari http://www.ocbc.id/id/article/2021/08/12/pendapatan-nasional-adalah</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>